# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
    - '*'

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

  - script: |
    cd client
    npm install
    npm run build
  displayName: 'Build Client'

- script: |
    cd server
    npm install
    npm run build
  displayName: 'Build Server'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Your Azure Subscription' # replace with your Azure subscription
    appType: 'webApp'
    WebAppName: 'Your Web App Name' # replace with your web app name
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip' # replace with the path to your package